# ***I - Mathematical operations with / without parentheses:***

1. **Mathematical operations without parentheses:**

Let's perform the following operation : -12.4 + 3.2 × 7.2 - 12.4 ÷ 3.2 + 1.4 × 5

+ **Step 1 :**

Complete all multiplication and division working from left to right. Perform : 3.2 × 7.2 and 12.4 ÷ 3.2 and 1.4 × 5

In [24]:
print('3.2 × 7.2 =',3.2*7.2)
print('12.4 ÷ 3.2 =',12.4/3.2)
print('1.4 × 5 =',1.4*5)

3.2 × 7.2 = 23.040000000000003
12.4 ÷ 3.2 = 3.875
1.4 × 5 = 7.0


+ **Step 2 :**

Complete all addition and subtraction working from left to right.Prform : -12.4 + 23.040000000000003 - 3.875 + 7.0

In [28]:
print('-12.4 + 23.040000000000003 - 3.875 + 7.0 =',-12.4 + 23.040000000000003 - 3.875 + 7.0)

-12.4 + 23.040000000000003 - 3.875 + 7.0 = 13.765000000000002


+ **Step 3 :**

The result

In [29]:
print('-12.4 + 3.2 × 7.2 - 12.4÷3.2 + 1.4×5 =',-12.4 + 3.2*7.2 - 12.4/3.2 + 1.4*5)

-12.4 + 3.2 × 7.2 - 12.4÷3.2 + 1.4×5 = 13.765000000000002


2. **Mathematical operations with parentheses :**

Let's perform the following operation : (-15.6 + 2.1) × 4.5 - 9.7 ÷ (5.2 - 0.4) + 6.2

+ **Step 1 :**

calculat the operation inside of the parentheses. Perform : -15.6 + 2.1 and 5.2 - 0.4

In [31]:
print('-15.6 + 2.1 =',-15.6 + 2.1)
print('  5.2 - 0.4 =',5.2 - 0.4)

-15.6 + 2.1 = -13.5
  5.2 - 0.4 = 4.8


+ **Step 2 :**

Complete all multiplication and division working from left to right. Perform : -13.5 × 4.5 and 9.7 ÷ 4.8

In [33]:
print('-13.5 × 4.5 =',-13.5*4.5)
print('9.7 ÷ 4.8 =',9.7/4.8)

-13.5 × 4.5 = -60.75
9.7 ÷ 4.8 = 2.0208333333333335


Complete all addition and subtraction working from left to right.Prform : -60.75 - 2.0208333333333335 + 6.2

In [34]:
print('-60.75 - 2.0208333333333335 + 6.2 =',-60.75 - 2.0208333333333335 + 6.2)

-60.75 - 2.0208333333333335 + 6.2 = -56.57083333333333


+ **Step 3 :**

The result

In [35]:
print('(-15.6 + 2.1) × 4.5 - 9.7 ÷ (5.2 - 0.4) + 6.2 =',(-15.6 + 2.1)*4.5 - 9.7/(5.2 - 0.4) + 6.2)

(-15.6 + 2.1) × 4.5 - 9.7 ÷ (5.2 - 0.4) + 6.2 = -56.57083333333333
